name: groupProject
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  ansicolor: ^2.0.1
  barbecue: ^0.4.0
  dart_console: ^1.0.0
  date_util: ^0.1.4
  encrypt: ^5.0.0
  http: ^0.13.3
  image: ^3.0.2
  
